# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '02:00'
    open-pull-requests-limit: 30
    labels:
      - dependencies
    ignore:
      # These should be grouped. Maintainer advise: Watch https://github.com/babel/babel
      # for new releases and file a PR if you got time.
      - dependency-name: '@babel/*'
        versions:
          - '>= 0'
      # https://github.com/mui-org/material-ui/pull/17604#issuecomment-536262291
      - dependency-name: core-js
        versions:
          - '>= 0'
      # These should be grouped once a PR for `jss` is opened
      - dependency-name: jss-*
        versions:
          - '>= 0'
      # These should be grouped. Maintainer advise: Watch https://github.com/dmtrKovalenko/date-io
      # for new releases and file a PR if you got time.
      - dependency-name: '@date-io/*'
        versions:
          - '>= 0'
      # 2.0 started using ES modules instead of CommonJS modules
      - dependency-name: raw-loader
        versions:
          - '>= 0'
      # not ignoring `react`. We'll hijack those PRs and also upgrade the other
      # packages in the facebook/react repository
      # should be grouped with `react`
      - dependency-name: react-dom
        versions:
          - '>= 0'
      # should be grouped with `react`
      - dependency-name: react-is
        versions:
          - '>= 0'
      # should be grouped with `react`
      - dependency-name: react-test-renderer
        versions:
          - '>= 0'
      # https://github.com/mui-org/material-ui/pull/17168#issuecomment-524861427
      - dependency-name: tslint
        versions:
          - 5.x
      # Should be grouped with @typescript-eslint/eslint-plugin
      # They sometimes are mergable independently but create a different dependency when merged leading to a changed yarn.lock
      # TODO: Revisit once https://github.com/dependabot/dependabot-core/issues/1190 is resolved.
      - dependency-name: '@typescript-eslint/parser'
        versions:
          - '>= 0'
