language: node_js
node_js:
  - "8"

before_install:
  - cd lib

env:
  - CMD='npm run test:date-fns'
  - CMD='npm run test:luxon'
  - CMD='npm run test:moment && codecov'
  - CMD='npm run test:typescript'
  - CMD='npm run build'
  - CMD='npx size-limit'
  - CMD='npm run lint'

script: $CMD
