language: node_js
node_js:
  - "8"

before_install:
  - cd lib

env:
  - CMD='test:date-fns'
  - CMD='test:luxon'
  - CMD='test:moment && npx codecov'
  - CMD='test:typescript'
  - CMD='build:analyze'
  - CMD='lint'

script: npm run $CMD
