language: node_js
node_js:
  - "8"

env:
  matrix:
    - UTILS=moment
    - UTILS=date-fns
    - UTILS=luxon

before_install:
  - cd lib

jobs:
  include:
    - stage: test
      script: npm run test && codecov

    - stage: build
      script: npm run build && size-limit

    - stage: lint
      script: npm run lint
