---
language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:coverage
  - bash <(curl -s https://codecov.io/bash) -f test/coverage/lcov.info
  - npm run test:karma
  - cd packages/material-ui-codemod && npm install && npm test
