language: node_js
node_js:
  - "8"

before_install:
  - cd lib

env:
  - CMD='UTILS=date-fns npm run test'
  - CMD='UTILS=moment npm run test'
  - CMD='UTILS=luxon npm run test'
  - CMD='npx codecov'
  - CMD='npm run test:typescript'
  - CMD='npm run build'
  - CMD='npx size-limit'
  - CMD='npm run lint'

script: $CMD
