language: node_js
node_js:
  - "8"

env:
  - CMD='test:date-fns'
  - CMD='test:luxon'
  - CMD='test:moment'
  - CMD='test:typescript'
  - CMD='build:analyze'
  - CMD='lint'

before_install:
  - cd lib

script: npm run $CMD
