---
language: node_js
node_js:
  - stable
sudo: required
dist: trusty
services:
  - docker
addons:
  artifacts:
    paths:
    - test/regressions/screenshots/output
cache:
  directories:
    - node_modules
    - docs/site/node_modules
    - test/regressions/site/node_modules
before_install:
  - cd test && docker-compose up -d chrome && cd ../

install:
  - npm install
  - cd docs/site && npm install && cd ../../
  - cd test/regressions/site && npm install && cd ../../../
script:
  - ./scripts/run-travis-tests.sh
after_success:
  - cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
