language: node_js
node_js:
  - "8"

env:
  - UTILS=date-fns
  - UTILS=moment
  - UTILS=luxon

before_install:
  - cd lib

script: npm run test && npx codecov

jobs:
  include:
    - stage: typescript
      script: npm run typescript

    - stage: build
      script: npm run build && size-limit

    - stage: lint
      script: npm run lint
