####
# Defaults
####
defaults: &js_defaults
  docker:
    - image: circleci/node:lts
      environment:
        ## this enables colors in the output
        TERM: xterm
  working_directory: ~/material-ui-pickers

version: 2
jobs:
  ####
  # Custom jobs
  ####
  checkout_code:
    <<: *js_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  javascript:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      # - restore_cache:
      #     keys:
      #       - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
      #       - v1-deps-{{ .Branch }}
      #       - v1-deps
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      # - run: yarn lint
      - run: yarn workspace material-ui-pickers build:analyze
      - persist_to_workspace:
          root: .
          paths: .

  test_cypress:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/material-ui-pickers

    steps:
      - run: yarn workspace docs build
      - run: yarn workspace docs start & npx wait-on http://localhost:3000 && yarn e2e:run --record

####
# Worflow
####
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - javascript:
          requires:
            - checkout_code

      - test_cypress:
          requires:
            - javascript

      # - test_moment:
      #     <<: *js_defaults
      #     requires:
      #       - javascript
      #     steps:
      #       - run: cd lib && yarn test:moment

      # - test_date-fns:
      #     <<: *js_defaults
      #     requires:
      #       - javascript
      #     steps:
      #       - run: cd lib && yarn test:date-fns

      # - test_luxon:
      #     <<: *js_defaults
      #     requires:
      #       - javascript
      #     steps:
      #       - run: cd lib && yarn test:luxon
