####################
# Defaults
####################
defaults: &js_defaults
  docker:
    - image: circleci/node:lts
      environment:
        ## this enables colors in the output
        TERM: xterm
  working_directory: ~/material-ui-pickers

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1

####################
# Custom jobs
####################
jobs:
  checkout_code:
    <<: *js_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  javascript:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache

      # - run: yarn lint
      - run: yarn workspace material-ui-pickers build:analyze
      - persist_to_workspace:
          root: .
          paths:
            - .
            - ~/.cache

  test_moment:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - run: cd lib && yarn test:moment -- -- --runInBand

  test_date-fns:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - run: cd lib && yarn test:date-fns -- -- --runInBand
      - run: cd lib && npx codecov

  test_luxon:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - run: cd lib && yarn test:luxon -- -- --runInBand

####################
# Workflow
####################
workflows:
  build_and_test:
    jobs:
      - checkout_code
      - javascript:
          requires:
            - checkout_code

      - cypress/run:
          name: 'Cypress tests'
          requires:
            - javascript
          executor: cypress/browsers-chrome69
          build: 'yarn workspace docs build'
          start: 'yarn workspace docs start'
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: true
          yarn: true

      - test_moment:
          requires:
            - javascript

      - test_date-fns:
          requires:
            - javascript

      - test_luxon:
          requires:
            - javascript
