####################
# Defaults
####################
defaults: &js_defaults
  docker:
    - image: circleci/node:lts
      environment:
        ## this enables colors in the output
        TERM: xterm
  working_directory: ~/material-ui-pickers

version: 2
####################
# Custom jobs
####################
jobs:
  checkout_code:
    <<: *js_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  javascript:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache

      # - run: yarn lint
      - run: yarn workspace material-ui-pickers build:analyze
      - persist_to_workspace:
          root: .
          paths: .

  test_cypress:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/material-ui-pickers

    steps:
      - attach_workspace:
          at: .
      - run: yarn workspace docs build
      - run: yarn workspace docs start & npx wait-on http://localhost:3000 && yarn e2e:run --record

  test_moment:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - run: cd lib && yarn test:moment -- -- --runInBand

  test_date-fns:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - run: cd lib && yarn test:date-fns -- -- --runInBand
      - run: cd lib && npx codecov

  test_luxon:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: .
      - run: cd lib && yarn test:luxon -- -- --runInBand

####################
# Workflow
####################
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - javascript:
          requires:
            - checkout_code

      - test_cypress:
          requires:
            - javascript

      - test_moment:
          requires:
            - javascript

      - test_date-fns:
          requires:
            - javascript

      - test_luxon:
          requires:
            - javascript
