defaults: &defaults
  working_directory: /tmp/material-ui
  docker:
    - image: circleci/node:6.11
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      # Fetch the code
      - checkout
      - run:
          name: Check versions and env
          command: |
            yarn --version
            node --version
            docker --version
            docker-compose --version
            env
            yarn cache dir
      - restore_cache:
          key: yarn-sha-{{ checksum "yarn.lock" }}
      - run:
          name: Install js dependencies
          command: |
            yarn install --pure-lockfile
            cd docs && yarn install --pure-lockfile
      - save_cache:
          key: yarn-sha-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v1
      - persist_to_workspace:
          root: /tmp/material-ui
          paths:
            - material-ui
  test_unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/material-ui
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Flow
          command: yarn flow
      - run:
          name: Tests fake browser
          command: yarn test:coverage
      - run:
          name: Check coverage generated
          command: |
            if ! [[ -s coverage/lcov.info ]]
            then
              exit 1
            fi
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash)
  test_browser:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/material-ui
      - run:
          name: Tests real browsers
          command: yarn test:karma
      - run:
          name: Can we generate the build?
          command: yarn build
      - run:
          name: Is the size acceptable?
          command: yarn size
      - run:
          name: Can we generate the docs?
          command: yarn build:docs
  test_regressions:
    <<: *defaults
    docker:
      - image: circleci/node:6.11
      - image: selenium/standalone-chrome:3.4.0
    steps:
      - attach_workspace:
          at: /tmp/material-ui
      - run:
          name: Visual regression tests
          command: |
            DOCKER_TEST_URL=http://$(ip addr show lo | grep "inet\b" | awk '{print $2}' | cut -d/ -f1):3090 yarn test:regressions
            yarn argos
workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - test_unit:
          requires:
            - checkout
      - test_browser:
          requires:
            - checkout
      - test_regressions:
          requires:
            - test_unit
            - test_browser
