name: Check if PR has label

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  test-label-applied:
    # Tests that label is added on the PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: mnajdova/github-action-required-labels@ca0df9249827e43aa4b4a0d25d9fe3e9b19b0705 # tag=v2.1
        with:
          mode: minimum
          count: 1
          labels: ''
