name: CI

on: [push, pull_request]

jobs:
  # Tests dev-only scripts across all supported dev environments
  test-dev:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn release:build
