name: CI

on:
  push:
    branches-ignore:
      # Dependabot branches are always Pull Requests.
      # We don't need to run CI twice (push+pull_request)
      - 'dependabot/**'
  pull_request:

jobs:
  # Tests dev-only scripts across all supported dev environments
  test-dev:
    # l10nbot does not affect dev scripts.
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@v2
        with:
          # fetch all tags which are required for `yarn release:changelog`
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
        env:
          # Don't need playwright in this job
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: yarn release:build
      - run: yarn release:changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: yarn release:tag
        run: |
          git remote -v
          yarn release:tag --dryRun
