name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  label-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: remove labels
        if: github.event.label.name == 'duplicate'
        uses: actions-cool/issues-helper@v1.7
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'status: incomplete,status: needs triage'
