name: 'Maintenance'
on:
  # So that PRs touching the same files as the push are updated
  push:
    branches-ignore:
      # PRs are almost never based off of dependabot PRs
      - 'dependabot/**'
  # So that the `dirtyLabel` is removed if conflicts are resolved
  # Could put too much strain on rate limit
  # If we hit the rate limit too often remove this event
  pull_request_target:
    branches-ignore:
      # These PRs are almost fully automated so labelling them is not as important.
      # They do burst the GitHub API though so we're ignoring them to not hit the rate limit
      - 'dependabot/**'
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: 'PR: out-of-date'
          removeOnDirtyLabel: 'PR: ready to ship'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          retryAfter: 130
          retryMax: 10
